/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

/**
 *
 * @author anton
 */
public class CadastroGeral extends javax.swing.JFrame {

    /**
     * Creates new form CadastroDePaciente
     */
    public CadastroGeral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        TxtCodigo = new javax.swing.JTextField();
        TxtCodigo1 = new javax.swing.JTextField();
        TxtNomeCliente = new javax.swing.JTextField();
        TxtSobrenomeCliente = new javax.swing.JTextField();
        TxtEmailCliente = new javax.swing.JTextField();
        TxtCPFCliente = new javax.swing.JTextField();
        PswSenhaCliente = new javax.swing.JPasswordField();
        PswSenhaCliente1 = new javax.swing.JPasswordField();
        BtnNovo1 = new javax.swing.JButton();
        BtnSalvar1 = new javax.swing.JButton();
        BtnEditar1 = new javax.swing.JButton();
        BtnExcluir1 = new javax.swing.JButton();
        BtnCancelar1 = new javax.swing.JButton();
        BtnVoltar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        TxtCargoFuncionario = new javax.swing.JTextField();
        TxtCodigo2 = new javax.swing.JTextField();
        TxtCodigo3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Senha :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Confirme sua senha :");

        jPanel1.setBackground(new java.awt.Color(3, 175, 239));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setBackground(new java.awt.Color(3, 175, 239));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Cadastro e Edição de Perfis");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        TxtCodigo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TxtCodigo.setForeground(new java.awt.Color(102, 102, 102));
        TxtCodigo.setText("ID Usuario");
        TxtCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 8))); // NOI18N
        TxtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtCodigoFocusGained(evt);
            }
        });
        TxtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCodigoActionPerformed(evt);
            }
        });

        TxtCodigo1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TxtCodigo1.setForeground(new java.awt.Color(102, 102, 102));
        TxtCodigo1.setText("Perfil");
        TxtCodigo1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Perfil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 8))); // NOI18N
        TxtCodigo1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtCodigo1FocusGained(evt);
            }
        });
        TxtCodigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCodigo1ActionPerformed(evt);
            }
        });

        TxtNomeCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TxtNomeCliente.setForeground(new java.awt.Color(102, 102, 102));
        TxtNomeCliente.setText("Nome");
        TxtNomeCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nome", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 8))); // NOI18N
        TxtNomeCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtNomeClienteFocusGained(evt);
            }
        });
        TxtNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNomeClienteActionPerformed(evt);
            }
        });

        TxtSobrenomeCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TxtSobrenomeCliente.setForeground(new java.awt.Color(102, 102, 102));
        TxtSobrenomeCliente.setText("Sobrenome");
        TxtSobrenomeCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sobrenome", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 8))); // NOI18N
        TxtSobrenomeCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtSobrenomeClienteFocusGained(evt);
            }
        });
        TxtSobrenomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSobrenomeClienteActionPerformed(evt);
            }
        });

        TxtEmailCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TxtEmailCliente.setForeground(new java.awt.Color(102, 102, 102));
        TxtEmailCliente.setText("Email");
        TxtEmailCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 8))); // NOI18N
        TxtEmailCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtEmailClienteFocusGained(evt);
            }
        });

        TxtCPFCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TxtCPFCliente.setForeground(new java.awt.Color(102, 102, 102));
        TxtCPFCliente.setText("CPF");
        TxtCPFCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CPF", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 8))); // NOI18N
        TxtCPFCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtCPFClienteFocusGained(evt);
            }
        });

        PswSenhaCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        PswSenhaCliente.setText("jPasswordField1");
        PswSenhaCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 8))); // NOI18N
        PswSenhaCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PswSenhaClienteFocusGained(evt);
            }
        });

        PswSenhaCliente1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        PswSenhaCliente1.setText("jPasswordField1");
        PswSenhaCliente1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 8))); // NOI18N
        PswSenhaCliente1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PswSenhaCliente1FocusGained(evt);
            }
        });

        BtnNovo1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnNovo1.setText("Novo");
        BtnNovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNovo1ActionPerformed(evt);
            }
        });

        BtnSalvar1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnSalvar1.setText("Salvar");
        BtnSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvar1ActionPerformed(evt);
            }
        });

        BtnEditar1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnEditar1.setText("Editar");
        BtnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditar1ActionPerformed(evt);
            }
        });

        BtnExcluir1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnExcluir1.setText("Excluir");
        BtnExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluir1ActionPerformed(evt);
            }
        });

        BtnCancelar1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnCancelar1.setText("Cancelar");
        BtnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelar1ActionPerformed(evt);
            }
        });

        BtnVoltar.setBackground(new java.awt.Color(204, 204, 204));
        BtnVoltar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BtnVoltar.setForeground(new java.awt.Color(51, 51, 51));
        BtnVoltar.setText("Voltar");

        jComboBox1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paciente", "Funcionario", "Médico", "Administrador" }));

        TxtCargoFuncionario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TxtCargoFuncionario.setForeground(new java.awt.Color(102, 102, 102));
        TxtCargoFuncionario.setText("Cargo");
        TxtCargoFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cargo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 8))); // NOI18N
        TxtCargoFuncionario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtCargoFuncionarioFocusGained(evt);
            }
        });

        TxtCodigo2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TxtCodigo2.setForeground(new java.awt.Color(102, 102, 102));
        TxtCodigo2.setText("ID Administrador");
        TxtCodigo2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID Administrador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 8))); // NOI18N
        TxtCodigo2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtCodigo2FocusGained(evt);
            }
        });
        TxtCodigo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCodigo2ActionPerformed(evt);
            }
        });

        TxtCodigo3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TxtCodigo3.setForeground(new java.awt.Color(102, 102, 102));
        TxtCodigo3.setText("ID Médico");
        TxtCodigo3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID Médico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 8))); // NOI18N
        TxtCodigo3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtCodigo3FocusGained(evt);
            }
        });
        TxtCodigo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCodigo3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TxtCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TxtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TxtSobrenomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(BtnNovo1)
                        .addGap(63, 63, 63)
                        .addComponent(BtnSalvar1)
                        .addGap(76, 76, 76)
                        .addComponent(BtnEditar1)
                        .addGap(58, 58, 58)
                        .addComponent(BtnExcluir1)
                        .addGap(47, 47, 47)
                        .addComponent(BtnCancelar1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(TxtCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TxtCargoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(PswSenhaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(PswSenhaCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtCodigo3, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(BtnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtSobrenomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCPFCliente))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PswSenhaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PswSenhaCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCargoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(TxtCodigo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnNovo1)
                    .addComponent(BtnSalvar1)
                    .addComponent(BtnEditar1)
                    .addComponent(BtnExcluir1)
                    .addComponent(BtnCancelar1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtCodigoFocusGained

        TxtCodigo.setText("");
    }//GEN-LAST:event_TxtCodigoFocusGained

    private void TxtCodigo1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtCodigo1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCodigo1FocusGained

    private void TxtCodigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCodigo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCodigo1ActionPerformed

    private void TxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCodigoActionPerformed

    private void TxtNomeClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtNomeClienteFocusGained

        TxtNomeCliente.setText("");

    }//GEN-LAST:event_TxtNomeClienteFocusGained

    private void TxtNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNomeClienteActionPerformed

    private void TxtSobrenomeClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtSobrenomeClienteFocusGained

        TxtSobrenomeCliente.setText("");

    }//GEN-LAST:event_TxtSobrenomeClienteFocusGained

    private void TxtSobrenomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSobrenomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSobrenomeClienteActionPerformed

    private void TxtEmailClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtEmailClienteFocusGained

        TxtEmailCliente.setText("");

    }//GEN-LAST:event_TxtEmailClienteFocusGained

    private void TxtCPFClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtCPFClienteFocusGained

        TxtCPFCliente.setText("");

    }//GEN-LAST:event_TxtCPFClienteFocusGained

    private void PswSenhaClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PswSenhaClienteFocusGained

        PswSenhaCliente.setText("");

    }//GEN-LAST:event_PswSenhaClienteFocusGained

    private void PswSenhaCliente1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PswSenhaCliente1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_PswSenhaCliente1FocusGained

    private void BtnNovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNovo1ActionPerformed

    }//GEN-LAST:event_BtnNovo1ActionPerformed

    private void BtnSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvar1ActionPerformed

    }//GEN-LAST:event_BtnSalvar1ActionPerformed

    private void BtnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditar1ActionPerformed

    }//GEN-LAST:event_BtnEditar1ActionPerformed

    private void BtnExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluir1ActionPerformed

    }//GEN-LAST:event_BtnExcluir1ActionPerformed

    private void BtnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelar1ActionPerformed

    }//GEN-LAST:event_BtnCancelar1ActionPerformed

    private void TxtCargoFuncionarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtCargoFuncionarioFocusGained

        TxtCargoFuncionario.setText("");

    }//GEN-LAST:event_TxtCargoFuncionarioFocusGained

    private void TxtCodigo2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtCodigo2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCodigo2FocusGained

    private void TxtCodigo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCodigo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCodigo2ActionPerformed

    private void TxtCodigo3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtCodigo3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCodigo3FocusGained

    private void TxtCodigo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCodigo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCodigo3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroGeral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar1;
    private javax.swing.JButton BtnEditar1;
    private javax.swing.JButton BtnExcluir1;
    private javax.swing.JButton BtnNovo1;
    private javax.swing.JButton BtnSalvar1;
    private javax.swing.JButton BtnVoltar;
    public static javax.swing.JPasswordField PswSenhaCliente;
    public static javax.swing.JPasswordField PswSenhaCliente1;
    public static javax.swing.JTextField TxtCPFCliente;
    public static javax.swing.JTextField TxtCargoFuncionario;
    public static javax.swing.JTextField TxtCodigo;
    public static javax.swing.JTextField TxtCodigo1;
    public static javax.swing.JTextField TxtCodigo2;
    public static javax.swing.JTextField TxtCodigo3;
    public static javax.swing.JTextField TxtEmailCliente;
    public static javax.swing.JTextField TxtNomeCliente;
    public static javax.swing.JTextField TxtSobrenomeCliente;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
